import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV generated by your C++ experiment runner
df = pd.read_csv("../../results/pso/pso_runtime.csv")

# Expecting columns: n,runtime
n = df["n"]
runtime = df["runtime"]

plt.figure(figsize=(8, 5))
plt.plot(n, runtime, marker='o', linestyle='-', color='blue')

plt.title("PSO Runtime vs Dataset Size (n)")
plt.xlabel("Dataset Size (n)")
plt.ylabel("Runtime (seconds)")
plt.grid(True)

# Save the graph
plt.savefig("runtime_vs_n.png", dpi=300)
plt.show()